<default: &default
  adapter:  postgresql
  encoding: unicode
  host: 0.0.0.0
  username: benjamin_balanger
  password: Lavoisier8

development:
 <<: *default
 database: nimley_dev

test:
 <<: *default
 database: nimley_test

production:
 <<: *default
 database: nimley_prod
